{
  "url": "https://api.github.com/repos/shap/shap/issues/2191",
  "repository_url": "https://api.github.com/repos/shap/shap",
  "labels_url": "https://api.github.com/repos/shap/shap/issues/2191/labels{/name}",
  "comments_url": "https://api.github.com/repos/shap/shap/issues/2191/comments",
  "events_url": "https://api.github.com/repos/shap/shap/issues/2191/events",
  "html_url": "https://github.com/shap/shap/issues/2191",
  "id": 1003145602,
  "node_id": "I_kwDOBHDcK847ysmC",
  "number": 2191,
  "title": " ImportError: No module named deep_tf",
  "user": {
    "login": "Brijesh-S",
    "id": 88571856,
    "node_id": "MDQ6VXNlcjg4NTcxODU2",
    "avatar_url": "https://avatars.githubusercontent.com/u/88571856?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Brijesh-S",
    "html_url": "https://github.com/Brijesh-S",
    "followers_url": "https://api.github.com/users/Brijesh-S/followers",
    "following_url": "https://api.github.com/users/Brijesh-S/following{/other_user}",
    "gists_url": "https://api.github.com/users/Brijesh-S/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Brijesh-S/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Brijesh-S/subscriptions",
    "organizations_url": "https://api.github.com/users/Brijesh-S/orgs",
    "repos_url": "https://api.github.com/users/Brijesh-S/repos",
    "events_url": "https://api.github.com/users/Brijesh-S/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Brijesh-S/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 0,
  "created_at": "2021-09-21T19:38:05Z",
  "updated_at": "2021-09-21T19:38:05Z",
  "closed_at": null,
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "I was trying to run the DeepExplainer example (Compute importance scores) from SHAP.\r\n(https://shap-lrjball.readthedocs.io/en/latest/example_notebooks/deep_explainer/DeepExplainer%20Genomics%20Example.html)\r\n\r\nI get the following error.\r\n\r\nI checked for the deep_tf.py file in the shap/explainers/deep folder and it is present there. But while importing the deef_tf, it gives import Error\r\n\r\nI am using python 2.7 , deeplift 0.6.12.0 and shap 0.28.5\r\n\r\nKindly Help!\r\n![image](https://user-images.githubusercontent.com/88571856/134234435-5474c371-c23f-4544-ab72-e4c6ad38dabe.png)",
  "closed_by": null,
  "reactions": {
    "url": "https://api.github.com/repos/shap/shap/issues/2191/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/shap/shap/issues/2191/timeline",
  "performed_via_github_app": null,
  "state_reason": null
}
