{
  "url": "https://api.github.com/repos/shap/shap/issues/2308",
  "repository_url": "https://api.github.com/repos/shap/shap",
  "labels_url": "https://api.github.com/repos/shap/shap/issues/2308/labels{/name}",
  "comments_url": "https://api.github.com/repos/shap/shap/issues/2308/comments",
  "events_url": "https://api.github.com/repos/shap/shap/issues/2308/events",
  "html_url": "https://github.com/shap/shap/issues/2308",
  "id": 1073343722,
  "node_id": "I_kwDOBHDcK84_-ezq",
  "number": 2308,
  "title": "How to plot force_plot of multiple samples?",
  "user": {
    "login": "VEZcoding",
    "id": 75246383,
    "node_id": "MDQ6VXNlcjc1MjQ2Mzgz",
    "avatar_url": "https://avatars.githubusercontent.com/u/75246383?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/VEZcoding",
    "html_url": "https://github.com/VEZcoding",
    "followers_url": "https://api.github.com/users/VEZcoding/followers",
    "following_url": "https://api.github.com/users/VEZcoding/following{/other_user}",
    "gists_url": "https://api.github.com/users/VEZcoding/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/VEZcoding/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/VEZcoding/subscriptions",
    "organizations_url": "https://api.github.com/users/VEZcoding/orgs",
    "repos_url": "https://api.github.com/users/VEZcoding/repos",
    "events_url": "https://api.github.com/users/VEZcoding/events{/privacy}",
    "received_events_url": "https://api.github.com/users/VEZcoding/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 1,
  "created_at": "2021-12-07T13:18:37Z",
  "updated_at": "2023-04-05T09:34:41Z",
  "closed_at": "2021-12-08T10:37:31Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "I wish to save force_plot of multiple samples, but it saves blank png. When I try to do matplotlib = True I get an excepion:  `Exception: matplotlib = True is not yet supported for force plots with multiple samples! `\r\n\r\nAny other ways to save the plot?\r\n\r\n",
  "closed_by": {
    "login": "VEZcoding",
    "id": 75246383,
    "node_id": "MDQ6VXNlcjc1MjQ2Mzgz",
    "avatar_url": "https://avatars.githubusercontent.com/u/75246383?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/VEZcoding",
    "html_url": "https://github.com/VEZcoding",
    "followers_url": "https://api.github.com/users/VEZcoding/followers",
    "following_url": "https://api.github.com/users/VEZcoding/following{/other_user}",
    "gists_url": "https://api.github.com/users/VEZcoding/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/VEZcoding/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/VEZcoding/subscriptions",
    "organizations_url": "https://api.github.com/users/VEZcoding/orgs",
    "repos_url": "https://api.github.com/users/VEZcoding/repos",
    "events_url": "https://api.github.com/users/VEZcoding/events{/privacy}",
    "received_events_url": "https://api.github.com/users/VEZcoding/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/shap/shap/issues/2308/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/shap/shap/issues/2308/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
