{
  "url": "https://api.github.com/repos/shap/shap/issues/30",
  "repository_url": "https://api.github.com/repos/shap/shap",
  "labels_url": "https://api.github.com/repos/shap/shap/issues/30/labels{/name}",
  "comments_url": "https://api.github.com/repos/shap/shap/issues/30/comments",
  "events_url": "https://api.github.com/repos/shap/shap/issues/30/events",
  "html_url": "https://github.com/shap/shap/issues/30",
  "id": 293982092,
  "node_id": "MDU6SXNzdWUyOTM5ODIwOTI=",
  "number": 30,
  "title": "shap.visualize issue",
  "user": {
    "login": "andrewwlong",
    "id": 29262537,
    "node_id": "MDQ6VXNlcjI5MjYyNTM3",
    "avatar_url": "https://avatars.githubusercontent.com/u/29262537?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/andrewwlong",
    "html_url": "https://github.com/andrewwlong",
    "followers_url": "https://api.github.com/users/andrewwlong/followers",
    "following_url": "https://api.github.com/users/andrewwlong/following{/other_user}",
    "gists_url": "https://api.github.com/users/andrewwlong/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/andrewwlong/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/andrewwlong/subscriptions",
    "organizations_url": "https://api.github.com/users/andrewwlong/orgs",
    "repos_url": "https://api.github.com/users/andrewwlong/repos",
    "events_url": "https://api.github.com/users/andrewwlong/events{/privacy}",
    "received_events_url": "https://api.github.com/users/andrewwlong/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 3,
  "created_at": "2018-02-02T18:32:23Z",
  "updated_at": "2018-02-03T16:25:47Z",
  "closed_at": "2018-02-03T16:25:46Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "I can't seem to get shap.visualize to work for the second plot on the readme. I upgraded shap and xgboost. \r\n\r\nThis is the code I'm using and the error. Any help would be great. \r\n\r\n```\r\nimport xgboost\r\n# or import lightgbm\r\nimport sklearn.datasets\r\nimport shap\r\n\r\n# load JS visualization code to notebook\r\nshap.initjs() \r\n\r\n# train XGBoost or LightGBM model\r\nd = sklearn.datasets.load_boston()\r\nbst = xgboost.train({\"learning_rate\": 0.01}, xgboost.DMatrix(d.data, label=d.target), 100)\r\n# or bst = lightgbm.train({\"learning_rate\": 0.01}, lightgbm.Dataset(d.data, label=d.target), 10)\r\n\r\n# explain the model's prediction using SHAP values on the first 1000 training data samples\r\nshap_values = bst.predict(xgboost.DMatrix(d.data), pred_contribs=True)\r\n# or shap_values = bst.predict(d.data[0:1000,:], pred_contrib=True)\r\n\r\n# visualize the first prediction's explaination\r\nshap.visualize(shap_values[0,:], feature_names=d.feature_names, data=d.data[0,:])\r\n\r\n# visualize the training set predictions\r\nshap.visualize(shap_values, d.data)\r\n---------------------------------------------------------------------------\r\nIndexError                                Traceback (most recent call last)\r\n~\\AppData\\Local\\Continuum\\Anaconda3\\lib\\site-packages\\IPython\\core\\formatters.py in __call__(self, obj)\r\n    339                 pass\r\n    340             else:\r\n--> 341                 return printer(obj)\r\n    342             # Finally look for special method names\r\n    343             method = get_real_method(obj, self.print_method)\r\n\r\n~\\AppData\\Local\\Continuum\\Anaconda3\\lib\\site-packages\\iml\\visualizers.py in try_list_display(e)\r\n     66     def try_list_display(e):\r\n     67         if isinstance(e, collections.Sequence) and len(e) > 0 and isinstance(e[0], AdditiveExplanation):\r\n---> 68             return visualize(e).data\r\n     69         else:\r\n     70             return str(e) if old_list_formatter is None else old_list_formatter(e)\r\n\r\n~\\AppData\\Local\\Continuum\\Anaconda3\\lib\\site-packages\\iml\\visualizers.py in visualize(e)\r\n     54         return SimpleListVisualizer(e).html()\r\n     55     elif isinstance(e, collections.Sequence) and len(e) > 0 and isinstance(e[0], AdditiveExplanation):\r\n---> 56         return AdditiveForceArrayVisualizer(e).html()\r\n     57     else:\r\n     58         assert False, \"visualize() can only display Explanation objects (or arrays of them)!\"\r\n\r\n~\\AppData\\Local\\Continuum\\Anaconda3\\lib\\site-packages\\iml\\visualizers.py in __init__(self, arr)\r\n    169                 \"features\": {}\r\n    170             })\r\n--> 171             for i in filter(lambda j: e.effects[j] != 0 or e.instance.x[0,j] != 0, range(len(e.data.group_names))):\r\n    172                 self.data[\"explanations\"][-1][\"features\"][i] = {\r\n    173                     \"effect\": ensure_not_numpy(e.effects[i]),\r\n\r\n~\\AppData\\Local\\Continuum\\Anaconda3\\lib\\site-packages\\iml\\visualizers.py in <lambda>(j)\r\n    169                 \"features\": {}\r\n    170             })\r\n--> 171             for i in filter(lambda j: e.effects[j] != 0 or e.instance.x[0,j] != 0, range(len(e.data.group_names))):\r\n    172                 self.data[\"explanations\"][-1][\"features\"][i] = {\r\n    173                     \"effect\": ensure_not_numpy(e.effects[i]),\r\n\r\nIndexError: index 13 is out of bounds for axis 0 with size 13\r\n```",
  "closed_by": {
    "login": "slundberg",
    "id": 3740613,
    "node_id": "MDQ6VXNlcjM3NDA2MTM=",
    "avatar_url": "https://avatars.githubusercontent.com/u/3740613?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/slundberg",
    "html_url": "https://github.com/slundberg",
    "followers_url": "https://api.github.com/users/slundberg/followers",
    "following_url": "https://api.github.com/users/slundberg/following{/other_user}",
    "gists_url": "https://api.github.com/users/slundberg/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/slundberg/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/slundberg/subscriptions",
    "organizations_url": "https://api.github.com/users/slundberg/orgs",
    "repos_url": "https://api.github.com/users/slundberg/repos",
    "events_url": "https://api.github.com/users/slundberg/events{/privacy}",
    "received_events_url": "https://api.github.com/users/slundberg/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/shap/shap/issues/30/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/shap/shap/issues/30/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
