{
  "url": "https://api.github.com/repos/shap/shap/issues/944",
  "repository_url": "https://api.github.com/repos/shap/shap",
  "labels_url": "https://api.github.com/repos/shap/shap/issues/944/labels{/name}",
  "comments_url": "https://api.github.com/repos/shap/shap/issues/944/comments",
  "events_url": "https://api.github.com/repos/shap/shap/issues/944/events",
  "html_url": "https://github.com/shap/shap/issues/944",
  "id": 536938970,
  "node_id": "MDU6SXNzdWU1MzY5Mzg5NzA=",
  "number": 944,
  "title": "AttributeError: 'Index' object has no attribute 'to_list' in function decision_plot",
  "user": {
    "login": "davidgar",
    "id": 32150716,
    "node_id": "MDQ6VXNlcjMyMTUwNzE2",
    "avatar_url": "https://avatars.githubusercontent.com/u/32150716?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/davidgar",
    "html_url": "https://github.com/davidgar",
    "followers_url": "https://api.github.com/users/davidgar/followers",
    "following_url": "https://api.github.com/users/davidgar/following{/other_user}",
    "gists_url": "https://api.github.com/users/davidgar/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/davidgar/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/davidgar/subscriptions",
    "organizations_url": "https://api.github.com/users/davidgar/orgs",
    "repos_url": "https://api.github.com/users/davidgar/repos",
    "events_url": "https://api.github.com/users/davidgar/events{/privacy}",
    "received_events_url": "https://api.github.com/users/davidgar/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 7,
  "created_at": "2019-12-12T12:08:00Z",
  "updated_at": "2019-12-17T10:17:24Z",
  "closed_at": "2019-12-17T10:17:24Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "When trying to call the function \"shap.decision_plot\", I get the aforementioned error. It seems that it is an issue related to the use of \"to_list()\".\r\n\r\n`explainer = shap.TreeExplainer(rf_model)`\r\n`shap.decision_plot(explainer.expected_value[1], explainer.shap_values(X6.iloc[64])[1], X6.iloc[64])`\r\n\r\n\r\n> AttributeError                            Traceback (most recent call last)\r\n> <ipython-input-247-2128bd02d594> in <module>\r\n> ----> 1 shap.decision_plot(explainer.expected_value[1], explainer.shap_values(X6.iloc[64])[1], X6.iloc[64])\r\n> \r\n> ~\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\shap\\plots\\decision.py in decision_plot(base_value, shap_values, features, feature_names, feature_order, feature_display_range, highlight, link, plot_color, axis_color, y_demarc_color, alpha, color_bar, auto_size_plot, title, xlim, show, return_objects, ignore_warnings, matplotlib)\r\n>     323     elif str(type(features)) == \"<class 'pandas.core.series.Series'>\":\r\n>     324         if feature_names is None:\r\n> --> 325             feature_names = features.index.to_list()\r\n>     326         features = features.values\r\n>     327     elif isinstance(features, list):\r\n> \r\n> AttributeError: 'Index' object has no attribute 'to_list'\r\n\r\nAny help would be really appreciated.\r\nThank you very much.\r\n\r\nRegards,\r\nDavid",
  "closed_by": {
    "login": "davidgar",
    "id": 32150716,
    "node_id": "MDQ6VXNlcjMyMTUwNzE2",
    "avatar_url": "https://avatars.githubusercontent.com/u/32150716?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/davidgar",
    "html_url": "https://github.com/davidgar",
    "followers_url": "https://api.github.com/users/davidgar/followers",
    "following_url": "https://api.github.com/users/davidgar/following{/other_user}",
    "gists_url": "https://api.github.com/users/davidgar/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/davidgar/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/davidgar/subscriptions",
    "organizations_url": "https://api.github.com/users/davidgar/orgs",
    "repos_url": "https://api.github.com/users/davidgar/repos",
    "events_url": "https://api.github.com/users/davidgar/events{/privacy}",
    "received_events_url": "https://api.github.com/users/davidgar/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/shap/shap/issues/944/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/shap/shap/issues/944/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
